import struct


CAMERA_X = 640
CAMERA_Y = 480
CAMERA_PIXEL_COMPONENTS = 4

CAMERA_FRAME_SIZE_BYTES = CAMERA_X * CAMERA_Y * CAMERA_PIXEL_COMPONENTS
SPEED_VALUE_SIZE_BYTES = struct.calcsize('f')
STEERING_ANGLE_VALUE_SIZE_BYTES = struct.calcsize('f')
RECV_DATA_SIZE = CAMERA_FRAME_SIZE_BYTES + SPEED_VALUE_SIZE_BYTES + STEERING_ANGLE_VALUE_SIZE_BYTES
SEND_DATA_SIZE = SPEED_VALUE_SIZE_BYTES + STEERING_ANGLE_VALUE_SIZE_BYTES

SERVER_HOST = "localhost"
SERVER_PORT = 3333
SERVER_ADDR = (SERVER_HOST, SERVER_PORT)

CONTROL_FPS = 60
CONTROL_DTIME = 1 / CONTROL_FPS
RENDER_FPS = 60
RENDER_DTIME = 1 / RENDER_FPS
# ATM for testing purposes
GENERATOR_FPS = 60
GENERATOR_DTIME = 60 / GENERATOR_FPS
