CAMERA_X                = 640
CAMERA_Y                = 480
CAMERA_PIXEL_COMPONENTS = 4
CAMERA_FRAME_SIZE       = CAMERA_X * CAMERA_Y * CAMERA_PIXEL_COMPONENTS

SERVER_HOST = 'localhost'
SERVER_PORT = 3333
SERVER_ADDR = (SERVER_HOST, SERVER_PORT)